# -*- coding: utf-8 -*-
"""CLIENT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0II7Wkkg8MA35oeME6BVOvYkkEptiTe
"""
# Eisha Tir Raazia
# Sec C
# 17k-3730


import socket
s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.connect(socket.gethostname())
msg=s.recv(1024)
print(msg.decode("UTF-8"))