# -*- coding: utf-8 -*-
"""SERVER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FMhY4-KJC5aARZiUXQ6LD0XuptOfUFwS
"""

# Eisha Tir Raazia
# Sec C
# 17k-3730


import socket
s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.bind(socket.gethostname(),1024)
s.listen(5)
while true:
  clt, adr=s.accept()
  print(f"connection to {adr} established")
  clt.send(bytes("Socket Programming in PYTHON,"UTF-8"))